export default [
    {
        id: 1,
        title: '최전구 초상 및 관련 유물 ',
        kor: '채용신 외',
        eng: 'CHAE YoungSin et al.',
        year: '연도미상',
        imgurl: './img/collection/con5.jpg',
    },
    {
        id: 2,
        title: '검은 샹들리에 ',
        kor: '아이 웨이웨이',
        eng: 'AI Weiwei',
        year: '2017 - 2021',
        imgurl: './img/collection/con6.jpeg',
    },
    {
        id: 3,
        title: '마지막 한 입 ',
        kor: '박진아',
        eng: 'PARK Jina',
        year: '2008',
        imgurl: './img/collection/con7.jpg',
    },
    {
        id: 4,
        title: '짝-패',
        kor: '변순철',
        eng: 'BYUN Soonchoel',
        year: '2001(2023 인화)',
        imgurl: './img/collection/con8.jpg',
    },
    {
        id: 5,
        title: '회귀 SA07012',
        kor: '김창렬',
        eng: 'KIM Tschang-Yeul',
        year: '2007',
        imgurl: './img/collection/con1.jpg',
    },
    {
        id: 6,
        title: '4-Ⅵ-69 #65',
        kor: '김환기',
        eng: 'KIM Whanki',
        year: '1969',
        imgurl: './img/collection/con2.jpg',
    },
    {
        id: 7,
        title: '흙집(土家)',
        kor: '이항성',
        eng: 'LEE Hangsung',
        year: '1993',
        imgurl: './img/collection/con3.jpg',
    },
    {
        id: 8,
        title: '기명절지',
        kor: '이도영',
        eng: 'LEE DoYoung',
        year: '연도미상',
        imgurl: './img/collection/con4.jpg',
    },
];
